# -*- coding: utf-8 -*-
"""LAB task 3 DS&a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y641Tif61GMv2h4mCPVA973WzLNpV7oN
"""

#                                      ******************[ M AHSAN ALI 200901072 Section-B BSCS-01 ]******************
class Node:
  def __init__(self,data):
    self.data=data
    self.next=None
    
class linked_list:
  def __init__(self):
    self.head=None
  def push(self,data):
    create_node=Node(data)
    create_node.next=self.head
    self.head=create_node

  def search_push(self,data,key):
    check=self.head
   
    
    while(check):
      
      if check.data==key:
        
        break
      check=check.next

    new_node=Node(data)
    nt=check.next
    new_node.next=nt
    check.next=new_node

    
  def delete_end(self):
    Nodes=self.head
    reset=self.head
    while(Nodes):
      if Nodes.next==None:
        break
      Nodes=Nodes.next
    while(reset):
      if reset.next==Nodes:
        break
      reset=reset.next
    reset.next=None  

  def push_end(self,data):
    Nodes=self.head
    snd=self.head
    while(Nodes):
      if snd.next!=None:
        snd=snd.next
      Nodes=Nodes.next
    pushing_at_end=Node(data)
    snd.next=pushing_at_end

  def delete_front(self):
   self.head=self.head.next

  def delete_search(self,key):
    NEXT=self.head
    Previous=self.head
    while(NEXT):
      if NEXT.data==key:
        break
      NEXT=NEXT.next
    while(Previous):
      if Previous.next==NEXT:
        break
      Previous=Previous.next
    NEXT=NEXT.next
    Previous.next=NEXT

         


  def print_list(self):
    Nodes=self.head
    i=1
    while(Nodes):
      print('Node {}:'.format(i),Nodes.data)
      Nodes=Nodes.next
      i=i+1

if __name__=='__main__':
   maker=linked_list()
   maker.push(22)
   maker.push(233)
   maker.push(4445)
   maker.push_end(33443)
   print('Creating a list and printing:')
   maker.print_list()
   
   print('Printing after adding a number at end in list:') 
   print('\t****adding { 555 } to the end ****')
   maker.push_end(555)
   maker.print_list()
   

   print('Printing after adding a number at end in list:') 
   print('\t****adding { 178 } to the front ****')
   
   maker.push(178)
  
   maker.print_list()
   
   print('Printing after search pushing in list:') 
   print('\t****searching value [ 233 ] in the list & adding { 106 } after  [233] in the list****')
   maker.search_push(106,233)
   maker.print_list()
   print('Deleting first:') 
   print('****Deleting first Node from list **** ')
   maker.delete_front()
   maker.print_list()

   print('Deleting last:') 
   print('****Deleting last Node from list **** ')
   maker.delete_end()
   maker.print_list()

   print('Deleting arbitary:') 
   print('****Searching and Deleting Node [ 106 ] from the list  **** ')
   maker.delete_search(106)
   maker.print_list()